server {
    listen 80;
    listen [::]:80;
    server_name d.bigclouder.com www.d.bigclouder.com;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name d.bigclouder.com www.d.bigclouder.com;

    ssl_certificate /etc/nginx/certs/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/cert.key;

    root /var/www/drd_web;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(?:jpg|jpeg|png|gif|webp|css|js|ico|svg)$ {
        expires 30d;
        add_header Cache-Control "public";
        try_files $uri =404;
    }
}
