server {
    listen 80;
    server_name _;

    root /var/www/drd_web;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(?:jpg|jpeg|png|gif|webp|css|js|ico|svg)$ {
        expires 30d;
        add_header Cache-Control "public";
        try_files $uri =404;
    }
}
